name: Install

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  install:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        python-version: ["3.8", "3.10"]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-java@v4
        with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '21'
      - uses: antoniovazquezblanco/setup-ghidra@v2.0.4
      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install apt dependencies
        run: sudo apt install -y pkg-config libsentencepiece-dev
      - name: Install dependencies
        run: pip install -r requirements.txt
