name: Test DIRTY Ghidra's inference ability

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  test-inference:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        python-version: ["3.10", "3.11"]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - uses: actions/setup-java@v4
        with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '21'
      - uses: antoniovazquezblanco/setup-ghidra@v2.0.4

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install apt dependencies
        run: sudo apt-get install -y pkg-config libsentencepiece-dev libprotobuf-dev

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download Ghidrathon
        uses: robinraju/release-downloader@v1
        with:
        # The source repository path.
        # Expected format {owner}/{repo}
        # Default: ${{ github.repository }}
          repository: mandiant/Ghidrathon
          tag: v4.0.0
          fileName: '*.zip'

      - name: Install Ghidrathon
        run: |
          mkdir ghidrathon-tmp
          unzip Ghidrathon*.zip -d ghidrathon-tmp
          pip install -r ghidrathon-tmp/requirements.txt
          python ghidrathon-tmp/ghidrathon_configure.py $GHIDRA_INSTALL_DIR
          unzip ghidrathon-tmp/Ghidrathon*.zip -d $GHIDRA_INSTALL_DIR/Ghidra/Extensions
          #$GHIDRA_INSTALL_DIR/support/analyzeHeadless projects TmpProject -import /bin/ls
      
      - name: Make projects directory
        run: mkdir -p projects

      - name: Cache model files
        uses: actions/cache@v4
        with:
          path: data1.tar.bz2
          key: data1.tar.bz2

      - name: Download model files
        run: test -f data1.tar.bz2 || wget -O 'data1.tar.bz2' 'https://cmu.box.com/shared/static/nx9fyn8jx0i9p4bftw8f2giqlufnoyj5'
        
      - name: Extract model files
        run: tar -xvjf data1.tar.bz2 -C $GITHUB_WORKSPACE/dirty/

      - name: Run DIRTY
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless projects MyProject -import /bin/ls -postScript $GITHUB_WORKSPACE/scripts/DIRTY_infer.py $(pwd)/infer_success.txt
          test -f infer_success.txt
